package com.tecknobit.gluky.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF2EBFA5)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFB9EFE4)
val onPrimaryContainerLight = Color(0xFF00201B)
val secondaryLight = Color(0xFF4ECDC4)
val onSecondaryLight = Color(0xFF00201D)
val secondaryContainerLight = Color(0xFFCCF3EE)
val onSecondaryContainerLight = Color(0xFF00201C)
val tertiaryLight = Color(0xFF5BC0EB)
val onTertiaryLight = Color(0xFF001F2A)
val tertiaryContainerLight = Color(0xFFCDEFFF)
val onTertiaryContainerLight = Color(0xFF001F2A)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF8FEFB)
val onBackgroundLight = Color(0xFF191C1B)
val surfaceLight = Color(0xFFF8FEFB)
val onSurfaceLight = Color(0xFF191C1B)
val surfaceVariantLight = Color(0xFFDDE5E2)
val onSurfaceVariantLight = Color(0xFF414B48)
val outlineLight = Color(0xFF717A77)
val outlineVariantLight = Color(0xFFC1C9C6)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2D3230)
val inverseOnSurfaceLight = Color(0xFFEFF5F3)
val inversePrimaryLight = Color(0xFF73E0CD)
val surfaceDimLight = Color(0xFFE1E7E4)
val surfaceBrightLight = Color(0xFFF8FEFB)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF2F8F5)
val surfaceContainerLight = Color(0xFFE6ECE9)
val surfaceContainerHighLight = Color(0xFFD9DFDC)
val surfaceContainerHighestLight = Color(0xFFCDD3D0)

val primaryDark = Color(0xFF73E0CD)
val onPrimaryDark = Color(0xFF003730)
val primaryContainerDark = Color(0xFF005046)
val onPrimaryContainerDark = Color(0xFFB9EFE4)
val secondaryDark = Color(0xFFAAF0EA)
val onSecondaryDark = Color(0xFF003733)
val secondaryContainerDark = Color(0xFF1D4D48)
val onSecondaryContainerDark = Color(0xFFCCF3EE)
val tertiaryDark = Color(0xFFA1DFFC)
val onTertiaryDark = Color(0xFF003545)
val tertiaryContainerDark = Color(0xFF004D63)
val onTertiaryContainerDark = Color(0xFFCDEFFF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0F1513)
val onBackgroundDark = Color(0xFFDEE4E0)
val surfaceDark = Color(0xFF0F1513)
val onSurfaceDark = Color(0xFFDEE4E0)
val surfaceVariantDark = Color(0xFF3F4945)
val onSurfaceVariantDark = Color(0xFFBFC9C4)
val outlineDark = Color(0xFF89938E)
val outlineVariantDark = Color(0xFF3F4945)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDEE4E0)
val inverseOnSurfaceDark = Color(0xFF2B322F)
val inversePrimaryDark = Color(0xFF006D60)
val surfaceDimDark = Color(0xFF0F1513)
val surfaceBrightDark = Color(0xFF343B38)
val surfaceContainerLowestDark = Color(0xFF090F0D)
val surfaceContainerLowDark = Color(0xFF171D1B)
val surfaceContainerDark = Color(0xFF1B211F)
val surfaceContainerHighDark = Color(0xFF252B29)
val surfaceContainerHighestDark = Color(0xFF303634)

val greenLight = Color(0xFF4CAF50)
val greenDark = Color(0xFF81C784)

val redLight = Color(0xFFE53935)
val redDark = Color(0xFFEF9A9A)

val yellowLight = Color(0xFFFBC02D)
val yellowDark = Color(0xFFFFF176)
